
# To Run the application in Debug mode
debug: false


# Server Port Number
server:
  port: 8888
  servlet:
    context-path: /spring-oauth

# Log Level
logging:
  level:
    web: DEBUG
    sql: INFO
    org:
      hibernate:
        type: trace 
    
# Using Spring Profile , Based on the flag this will pick up the data source and execute the queries if any
spring:
# Disable Dev Tools by setting the value as false
  devtools:
    add-properties: false
  profiles:
    active:
    - dev
  main:
    banner-mode: console
# Spring Security Resource ID Name
custom:
  spring:
    resource_id = "RESOURCE_ID"

security:
  oauth2:
    authorization:
      check-token-access: permitAll    
---     
      
#Spring Data Source Configuration & Flyway Configuration
spring:
  profiles: dev
  datasource:
    initialization-mode: always 
    username: root
    password: tagit
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?userSSL=false
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  ssl:
    key-store : classpath:jgsudhakar.keystore
    enabled: false
    key-store-password: jgsudhakar
    key-alias: jgsudhakar
       